line-length = 120
target-version = "py39"
src = ["py/src", "py/tests", "scripts"]

[lint]
select = ["E", "F", "W", "I", "B", "UP", "SIM", "RUF"]
ignore = ["RUF001", "RUF002", "RUF003", "E501", "UP006", "UP007", "UP035", "UP045", "SIM108"]
