// Bundle the shared JSON data (single source of truth: <repo>/data)
// into TypeScript modules. The generated files are git-ignored and rebuilt by
// `npm run build` / `npm test`.
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, "..", "..", "data");
const outDir = join(here, "..", "src", "data");
mkdirSync(outDir, { recursive: true });

const readJson = (p) => JSON.parse(readFileSync(p, "utf8"));

// Embedding JSON as a string literal keeps the TypeScript compiler fast and is
// also the fastest way for JS engines to materialise large objects.
function emit(name, typeImport, typeName, value) {
  const literal = JSON.stringify(JSON.stringify(value));
  const body =
    `// Generated by scripts/gen-data.mjs from <repo>/data — do not edit.\n` +
    `import type { ${typeName.replace("[]", "")} } from "${typeImport}";\n\n` +
    `const data: ${typeName} = JSON.parse(${literal});\n` +
    `export default data;\n`;
  writeFileSync(join(outDir, `${name}.ts`), body);
  return Buffer.byteLength(literal);
}

const schemeFiles = readdirSync(join(dataDir, "schemes"))
  .filter((f) => f.endsWith(".json"))
  .sort();
const schemes = schemeFiles.map((f) => {
  const spec = readJson(join(dataDir, "schemes", f));
  if (`${spec.id}.json` !== f) throw new Error(`${f}: file name must be ${spec.id}.json`);
  return spec;
});
const nameFiles = readdirSync(join(dataDir, "names"))
  .filter((f) => f.endsWith(".json"))
  .sort();
const names = nameFiles.map((f) => ({ file: f, names: readJson(join(dataDir, "names", f)).names }));

const sizes = {
  schemes: emit("schemes", "../types.js", "SchemeSpec[]", schemes),
  names: emit("names", "../types.js", "LexiconFile[]", names),
  defaults: emit("defaults", "../types.js", "DefaultsConfig", readJson(join(dataDir, "defaults.json"))),
  variantRules: emit("variantRules", "../types.js", "VariantRulesFile", readJson(join(dataDir, "variant_rules.json"))),
};
const kb = Object.fromEntries(Object.entries(sizes).map(([k, v]) => [k, `${Math.round(v / 1024)} KB`]));
console.log(`gen-data: ${schemes.length} schemes, ${names.reduce((n, f) => n + f.names.length, 0)} names`, kb);
