"""Regenerate docs/SCHEMES.md from the bundled scheme files.

Usage: python scripts/gen_schemes_doc.py
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from translit_names import list_schemes
from translit_names._registry import defaults_config

LANG_NAMES = {
    "ru": "Russian",
    "uk": "Ukrainian",
    "be": "Belarusian",
    "bg": "Bulgarian",
    "sr": "Serbian",
    "mk": "Macedonian",
    "sh": "Serbo-Croatian (Latin)",
    "mul": "Any Latin-script language",
    "kk": "Kazakh",
    "ky": "Kyrgyz",
    "uz": "Uzbek",
    "tg": "Tajik",
    "tk": "Turkmen",
    "tr": "Turkish",
    "az": "Azerbaijani",
    "tt": "Tatar",
    "ba": "Bashkir",
    "ce": "Chechen / Ingush",
    "ar": "Arabic",
    "fa": "Persian (Farsi, Dari)",
    "ur": "Urdu",
    "ps": "Pashto",
}
ORDER = list(LANG_NAMES)


def main() -> None:
    defaults = defaults_config()["transliterate"]
    by_lang = defaultdict(list)
    for s in list_schemes():
        by_lang[s.language].append(s)
    lines = [
        "# Bundled schemes",
        "",
        "Generated by `scripts/gen_schemes_doc.py` \u2014 do not edit by hand.",
        "",
        f"**{sum(len(v) for v in by_lang.values())} schemes** for {len(by_lang)} languages. "
        "★ marks the default scheme used by `transliterate()` when no scheme is given.",
        "",
    ]
    for lang in sorted(by_lang, key=lambda x: (ORDER.index(x) if x in ORDER else 99, x)):
        lines += [f"## {LANG_NAMES.get(lang, lang)} (`{lang}`)", ""]
        lines += ["| Scheme | Title | Kind | Status | Year | Example |", "|---|---|---|---|---|---|"]
        for s in sorted(by_lang[lang], key=lambda s: (s.id != defaults.get(lang), s.id)):
            star = " ★" if defaults.get(lang) == s.id else ""
            example = ""
            if s.samples:
                short = [smp for smp in s.samples if len(smp[0]) <= 30]
                src, out = short[0] if short else min(s.samples, key=lambda smp: len(smp[0]))
                example = f"{src} → {out}".replace("|", "\\|")
            title = s.title.replace("|", "\\|")
            lines.append(f"| `{s.id}`{star} | {title} | {s.kind} | {s.status} | {s.year or ''} | {example} |")
        lines.append("")
    out = Path(__file__).resolve().parent.parent / "docs" / "SCHEMES.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
